"""
Django settings for PDF_Fuzz project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ASSETS_DIR = "assets"
ASSETS_DIR = "uploads"
UPLOADS_DIR = "uploads"
IMAGES_DIR = "images"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-iragklj(cdj0i+pzt&50))_dd%jlxbtn_=*8-)*fi8gh7u0c1z"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "fuzz",
    "chunkedUpload",
    "django_extensions",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    # 'django.middleware.csrf.CsrfViewMiddleware',
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "PDF_Fuzz.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "PDF_Fuzz.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


class IgnoreApiTest:
    def filter(self, record):

        igonore_list = [
            "health",
            "chunkedUpload",
        ]

        if any([item in record.getMessage() for item in igonore_list]):
            return False
        else:
            return True


logging.getLogger("django.server").addFilter(IgnoreApiTest())



# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


## Rest
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # 'rest_framework.authentication.TokenAuthentication', # Auth Token
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # <-- JWT Authentication
    ],
}

# CORS_ALLOWED_ORIGINS = ["http://localhost:3000", "http://localhost", "http://*"]
CORS_ALLOW_ALL_ORIGINS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ORIGIN_ALLOW_ALL = True
# CORS_ORIGIN_WHITELIST = (
#   'http://localhost:3000',
# )

CORS_ALLOW_HEADERS = [
    "*",
]


LOG_FILE_PATH = "logs/general.log"
# Fix for jupyter log  file resolution failure
if "/app" in __file__:
    LOG_FILE_PATH = "/app/logs/general.log"


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s [%(name)s:%(funcName)s] :: %(message)s"
            "%(process)d %(thread)d %(message)s"
        },
        "simple": {
            "format": "%(levelname)s %(asctime)s [%(name)s:%(funcName)s] :: %(message)s"
        },
    },
    "handlers": {
        # Send info level messages to console
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        # level DEBUG and higher
        # Disable this block if it django shell jupyter notebooks keep failing
        "file": {
            "class": "logging.FileHandler",
            "level": "INFO",
            "filename": LOG_FILE_PATH,
            "mode": "a",
            "formatter": "verbose",
        },
    },
    # maps to all loggers:
    # https://docs.djangoproject.com/en/5.0/howto/logging/#configure-a-logger-mapping
    "loggers": {
        "": {"level": "DEBUG", "handlers": ["console", "file"]},
    },  # logs capture and forwarding
}



CELERY_LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s [%(name)s:%(funcName)s] :: %(message)s"
            "%(process)d %(thread)d %(message)s"
        },
        "simple": {
            "format": "%(levelname)s %(asctime)s [%(name)s:%(funcName)s] :: %(message)s"
        },
    },
    "handlers": {
        # Send all messages to console
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        # level DEBUG and higher
        "file": {
            "class": "logging.FileHandler",
            "level": "INFO",
            "filename": "logs/celery-general.log",
            "mode": "w",
            "formatter": "simple",
        },
        "file-detailed": {
            "class": "logging.FileHandler",
            "level": "DEBUG",
            "filename": "logs/celery-detailed.log",
            "mode": "w",
            "formatter": "verbose",
        },
    },
    "celery": {"handlers": ["celery"], "level": "DEBUG", "propagate": False},
    "loggers": {
        "": {"level": "DEBUG", "handlers": ["console", "file", "file-detailed"]},
    },
}

